In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from scipy import stats
from scipy.stats import poisson, ttest_ind

##Reading the ZHVI file and creating a base dataframe.
msazhvi = pd.read_csv("MSAZHVI.csv")
msazhvi.head()

##Averaging out the 12 months in 2018 to obtain 1 value for the entire year.
msazhvi["2018 ZHVI"] = msazhvi["2018-01-31"] + msazhvi["2018-02-28"] + msazhvi["2018-03-31"] + msazhvi["2018-04-30"] + msazhvi["2018-05-31"] + msazhvi["2018-06-30"] + msazhvi["2018-07-31"] + msazhvi["2018-08-31"] + msazhvi["2018-09-30"] + msazhvi["2018-10-31"] + msazhvi["2018-11-30"] + msazhvi["2018-12-31"]
msazhvi["2018 ZHVI"]= msazhvi["2018 ZHVI"]/12

##Renaming columns
msazhvi = msazhvi[["RegionName", "2018 ZHVI"]]

##Choosing cities
msazhvi = msazhvi[msazhvi["RegionName"].isin(["New York, NY", "Chicago, IL", "Houston, TX", "Boston, MA", "Louisville-Jefferson County, KY", "Cincinnati, OH", "Washington, DC", "Denver, CO", "San Francisco, CA", "Los Angeles-Long Beach-Anaheim, CA", "Miami-Fort Lauderdale, FL", "Seattle, WA", "Atlanta, GA", "Detroit, MI", "Minneapolis, MN", "Phoenix, AZ", "St. Louis, MO", "Albuquerque, NM", "Birmingham, AL", "Boise City, ID", "Charlotte, NC", "Dallas-Fort Worth, TX", "Urban Honolulu, HI", "Kansas City, MO", "Las Vegas, NV", "Milwaukee, WI", "Nashville, TN", "Oklahoma City, OK", "Omaha, NE", "Pittsburgh, PA", "Salt Lake City, UT", "Tampa, FL"])]

##Creating columns to be filled
msazhvi["Mean HS/Equivalent Educated"] = np.nan
msazhvi["Mean Bachelor's Degree Holding"] = np.nan
msazhvi["Mean Postgraduate Educated"] = np.nan
msazhvi["Mean Income"] = np.nan
msazhvi["Mean Property Tax"] = np.nan
msazhvi["Mean Rent as a Percentage of Income"] = np.nan

In [39]:
def MSA_data_frame_builder(household, education):
    
    ##Education data set
    ed = pd.read_csv(education)
    ##Housing Data Set
    db = pd.read_csv(household)
    
    ##Column for percentage of population with a high school diploma
    hs_or_equivalent = []
    ##Column for percentage of population with a Bachelor's degree
    bachelors = []
    ##Column for percentage of population with a Postgraduate degree
    postgrad = []
    
    ##for loop that finds the percentages of the population for each column (since the data is raw values, not divided over population)
    for i in range(len(ed["Selected Geographies"])):
        percent = (ed["Regular high school diploma"][i] + ed["GED or alternative credential"][i])/ed["Total"][i]
        hs_or_equivalent.append(percent)
        percent = ed["Bachelor's degree"][i]/ ed["Total"][i]
        bachelors.append(percent)
        percent = (ed["Master's degree"][i] + ed["Professional degree beyond a bachelor's degree"][i] + ed["Doctorate degree"][i])/ ed["Total"][i]
        postgrad.append(percent)
    
    ##inserting averaged data into the data set
    db["HS/Equivalent Education Percentage"] = hs_or_equivalent
    db["Bachelor's Percentage"] = bachelors
    db["Postgraduate Percentage"] = postgrad
    db.insert(loc=2, column="Total Population", value=ed["Total"])
    return db


##creating datasets for each of our cities
SF = MSA_data_frame_builder("Michael's Data/SF.csv", "Michael's Data/SFEducation.csv")
LA = MSA_data_frame_builder("Michael's Data/LA.csv", "Michael's Data/LAEducation.csv")
DE = MSA_data_frame_builder("Michael's Data/Denver.csv", "Michael's Data/DenverEducation.csv")

NY = MSA_data_frame_builder("John's Data/NYC/NYC.csv", "John's Data/NYC/NYCEducation.csv")
BT = MSA_data_frame_builder("John's Data/Boston/Boston.csv", "John's Data/Boston/BostonEducation.csv")
CC = MSA_data_frame_builder("John's Data/Cincinnati/Cincinnati.csv", "John's Data/Cincinnati/CincinnatiEducation.csv")

DC = MSA_data_frame_builder("Patricio's Data/DC/DCHouses.csv", "Patricio's Data/DC/DCEducation.csv")
LV = MSA_data_frame_builder("Patricio's Data/Louisville/LouisvilleHouses.csv", "Patricio's Data/Louisville/LouisvilleEducation.csv")
ST = MSA_data_frame_builder("Patricio's Data/Seattle/SeattleHouses.csv", "Patricio's Data/Seattle/SeattleEducation.csv")

CH = MSA_data_frame_builder("Colin's Data/ChicagoData/Chicago.csv", "Colin's Data/ChicagoData/ChicagoEducation.csv")
HO = MSA_data_frame_builder("Colin's Data/HoustonData/Houston.csv", "Colin's Data/HoustonData/HoustonEducation.csv")
MI = MSA_data_frame_builder("Colin's Data/Miami-Ft.Lauderdale/Miami.csv", "Colin's Data/Miami-Ft.Lauderdale/MiamiEducation.csv")

ATL = MSA_data_frame_builder("Census Data/AtlantaHouses.csv", "Census Data/AtlantaEducation.csv")
DAL = MSA_data_frame_builder("Census Data/DallasHouses.csv", "Census Data/DallasEducation.csv")
DET = MSA_data_frame_builder("Census Data/DetroitHouses.csv", "Census Data/DetroitEducation.csv")
MN = MSA_data_frame_builder("Census Data/MinneapolisHouses.csv", "Census Data/MinneapolisEducation.csv")
PH = MSA_data_frame_builder("Census Data/PhoenixHouses.csv", "Census Data/PhoenixEducation.csv")
STL = MSA_data_frame_builder("Census Data/StLouisHouses.csv", "Census Data/StLouisEducation.csv")
ALB = MSA_data_frame_builder("Census Data/AlbuquerqueHouses.csv", "Census Data/AlbuquerqueEducation.csv")
BH = MSA_data_frame_builder("Census Data/BirminghamHouses.csv", "Census Data/BirminghamEducation.csv")
BO = MSA_data_frame_builder("Census Data/BoiseHouses.csv", "Census Data/BoiseEducation.csv")
CLT = MSA_data_frame_builder("Census Data/CharlotteHouses.csv", "Census Data/CharlotteEducation.csv")
HON = MSA_data_frame_builder("Census Data/HonoluluHouses.csv", "Census Data/HonoluluEducation.csv")
KC = MSA_data_frame_builder("Census Data/KansasCityHouses.csv", "Census Data/KansasCityEducation.csv")
LV = MSA_data_frame_builder("Census Data/LasVegasHouses.csv", "Census Data/LasVegasEducation.csv")
MIL = MSA_data_frame_builder("Census Data/MilwaukeeHouses.csv", "Census Data/MilwaukeeEducation.csv")
NSV = MSA_data_frame_builder("Census Data/NashvilleHouses.csv", "Census Data/NashvilleEducation.csv")
OKC = MSA_data_frame_builder("Census Data/OklahomaCityHouses.csv", "Census Data/OklahomaCityEducation.csv")
OM = MSA_data_frame_builder("Census Data/OmahaHouses.csv", "Census Data/OmahaEducation.csv")
PT = MSA_data_frame_builder("Census Data/PittsburghHouses.csv", "Census Data/PittsburghEducation.csv")
SLC = MSA_data_frame_builder("Census Data/SaltLakeHouses.csv", "Census Data/SaltLakeEducation.csv")
TP = MSA_data_frame_builder("Census Data/TampaHouses.csv", "Census Data/TampaEducation.csv")

In [44]:
##Function finds the weighted means of each Metropolitan Statistical Area (utilizing county data). Takes in a name and a dataframe
def weightedMeans(location, MSAdata):
    hs = 0
    bach = 0
    post = 0
    inc = 0
    tax = 0
    grpip = 0
    
    totalHouses = MSAdata["Households"].sum()
    totalPop = MSAdata["Total Population"].sum()
    
    for i in range(len(MSAdata.index)-1):
        hs += MSAdata["HS/Equivalent Education Percentage"][i]*MSAdata["Total Population"][i]/totalPop
        bach += MSAdata["Bachelor's Percentage"][i]*MSAdata["Total Population"][i]/totalPop
        post += MSAdata["Postgraduate Percentage"][i]*MSAdata["Total Population"][i]/totalPop
        inc += MSAdata["Household income (past 12 months, use ADJINC to adjust HINCP to constant dollars)"][i]*MSAdata["Households"][i]/totalHouses
        tax += MSAdata["Property taxes (yearly real estate taxes)"][i]*MSAdata["Households"][i]/totalHouses
        grpip += MSAdata["Gross rent as a percentage of household income past 12 months"][i]*MSAdata["Households"][i]/totalHouses
    
    msazhvi.loc[(msazhvi["RegionName"] == location), "Mean HS/Equivalent Educated"] = hs
    msazhvi.loc[(msazhvi["RegionName"] == location), "Mean Bachelor's Degree Holding"] = bach
    msazhvi.loc[(msazhvi["RegionName"] == location), "Mean Postgraduate Educated"] = post
    msazhvi.loc[(msazhvi["RegionName"] == location), "Mean Income"] = inc
    msazhvi.loc[(msazhvi["RegionName"] == location), "Mean Property Tax"] = tax
    msazhvi.loc[(msazhvi["RegionName"] == location), "Mean Rent as a Percentage of Income"] = grpip

weightedMeans("San Francisco, CA", SF)
weightedMeans("Los Angeles-Long Beach-Anaheim, CA", LA)
weightedMeans("Denver, CO", DE)

weightedMeans("New York, NY", NY)
weightedMeans("Boston, MA", BT)
weightedMeans("Cincinnati, OH", CC)

weightedMeans("Washington, DC", DC)
weightedMeans("Louisville-Jefferson County, KY", LV)
weightedMeans("Seattle, WA", ST)

weightedMeans("Chicago, IL", CH)
weightedMeans("Houston, TX", HO)
weightedMeans("Miami-Fort Lauderdale, FL", MI)

weightedMeans('Atlanta, GA', ATL)
weightedMeans('Dallas-Fort Worth, TX', DAL)
weightedMeans('Detroit, MI', DET)
weightedMeans('Minneapolis, MN', MN)
weightedMeans('Phoenix, AZ', PH)
weightedMeans('St. Louis, MO', STL)

weightedMeans('Albuquerque, NM', ALB)
weightedMeans('Birmingham, AL', BH)
weightedMeans('Boise City, ID', BO)
weightedMeans('Charlotte, NC', CLT)
weightedMeans('Urban Honolulu, HI', HON)
weightedMeans('Kansas City, MO', KC)
weightedMeans('Milwaukee, WI', MIL)
weightedMeans('Las Vegas, NV', LV)
weightedMeans('Nashville, TN', NSV)
weightedMeans('Oklahoma City, OK', OKC)
weightedMeans('Omaha, NE', OM)
weightedMeans('Pittsburgh, PA', PT)
weightedMeans('Salt Lake City, UT', SLC)
weightedMeans('Tampa, FL', TP)



msazhvi

,RegionName,2018 ZHVI,Mean HS/Equivalent Educated,Mean Bachelor's Degree Holding,Mean Postgraduate Educated,Mean Income,Mean Property Tax,Mean Rent as a Percentage of Income,Education Score
1,"New York, NY",4.702898e+05,0.191949,0.180329,0.123016,97641.232946,4064.339243,16.904336,0.799480
2,"Los Angeles-Long Beach-Anaheim, CA",6.584842e+05,0.161437,0.163677,0.082337,89949.963421,2458.409629,19.269835,0.645431
3,"Chicago, IL",2.363690e+05,0.192492,0.168804,0.104656,82888.935938,3580.639054,11.365745,0.737046
4,"Dallas-Fort Worth, TX",2.402137e+05,0.174826,0.155749,0.081528,81473.988890,2665.472588,13.052650,0.642689
6,"Houston, TX",2.076934e+05,0.176815,0.138221,0.076109,74356.187856,2460.132827,12.184813,0.600664
7,"Washington, DC",4.165819e+05,0.139137,0.193117,0.180565,120560.818279,2940.142413,12.535437,0.902046
8,"Miami-Fort Lauderdale, FL",2.871426e+05,0.202726,0.159232,0.098067,59572.771936,1796.829220,14.138335,0.714898
9,"Atlanta, GA",2.218861e+05,0.184920,0.169473,0.099729,79957.074418,1532.837861,11.776438,0.719347
10,"Boston, MA",4.790218e+05,0.163174,0.194791,0.159662,103301.029820,3285.172256,13.718253,0.881021
11,"San Francisco, CA",1.103116e+06,0.127812,0.229953,0.152991,131980.118375,3790.872647,14.226921,0.893607
12,"Detroit, MI",1.700893e+05,0.203338,0.142352,0.086832,64813.431403,1898.022214,9.551047,0.659284
14,"Phoenix, AZ",2.649902e+05,0.181454,0.141387,0.077424,69011.738829,1071.507305,10.857176,0.614025
15,"Seattle, WA",5.061742e+05,0.147645,0.197843,0.117782,102034.485722,2810.999842,13.163311,0.774660
18,"St. Louis, MO",1.707563e+05,0.199771,0.145148,0.095206,66511.644629,1669.364955,9.695862,0.680010
19,"Tampa, FL",2.140815e+05,0.231726,0.144599,0.076331,55370.108906,1238.679096,11.591063,0.667566
21,"Denver, CO",4.225489e+05,0.156835,0.199444,0.114301,110434.632370,1688.723471,11.666200,0.778727
22,"Pittsburgh, PA",1.508852e+05,0.258811,0.158058,0.099322,62802.432481,1846.930071,8.532649,NaN
24,"Charlotte, NC",2.163644e+05,0.172396,0.162015,0.077067,69397.335019,1249.384175,9.855507,0.641277
28,"Cincinnati, OH",1.728423e+05,0.230931,0.135901,0.082551,66424.547917,1619.872282,10.139453,0.665420
30,"Kansas City, MO",1.911785e+05,0.186945,0.162428,0.089786,70613.761126,1570.023993,10.461159,0.685823
31,"Las Vegas, NV",2.753374e+05,0.211076,0.102919,0.054356,58130.669357,898.955373,14.019232,0.521349
37,"Nashville, TN",2.612573e+05,0.196303,0.156477,0.078831,69291.708601,1081.216011,9.755528,0.659272
39,"Milwaukee, WI",1.873276e+05,0.197866,0.148636,0.086703,66112.263691,2173.899897,12.610596,0.664827
42,"Oklahoma City, OK",1.493187e+05,0.192448,0.122023,0.071672,59042.968269,1052.635663,10.784396,0.576935
43,"Louisville-Jefferson County, KY",1.692404e+05,0.211076,0.102919,0.054356,58130.669357,898.955373,14.019232,0.521349
49,"Birmingham, AL",1.535094e+05,0.181815,0.136035,0.075744,52330.707363,608.670042,7.961990,0.600889
50,"Salt Lake City, UT",3.469105e+05,0.173598,0.126562,0.069567,77119.756855,1263.801173,9.676134,0.561412
54,"Urban Honolulu, HI",7.059563e+05,0.192482,0.145256,0.077518,73568.187963,1060.433865,13.910909,0.632233
59,"Albuquerque, NM",1.943633e+05,0.165207,0.125597,0.096205,55570.829575,1164.921601,10.999068,0.612553
61,"Omaha, NE",1.817830e+05,0.167507,0.144893,0.078201,67291.585269,2091.525895,9.217720,0.608177
85,"Boise City, ID",2.674975e+05,0.187000,0.117333,0.049145,61374.068923,1191.112999,6.990748,NaN

In [45]:
msazhvi['Education Score'] = msazhvi['Mean HS/Equivalent Educated'] + 1.8*msazhvi["Mean Bachelor's Degree Holding"] + 2.3*msazhvi['Mean Postgraduate Educated']

In [46]:
model = LinearRegression()
model.fit(msazhvi[['Education Score', 'Mean Income', 'Mean Property Tax', 'Mean Rent as a Percentage of Income']], msazhvi['2018 ZHVI'])

LinearRegression()

In [47]:
print('Education Score Slope: ' + str(model.coef_[0]))
print('Income Slope: ' + str(model.coef_[1]))
print('Property Tax Slope: ' + str(model.coef_[2]))
print('RPI Slope: ' + str(model.coef_[3]))

Education Score Slope: -215188.69904800138
Income Slope: 8.836376106425709
Property Tax Slope: -50.77421885457578
RPI Slope: 27149.65622421254

In [48]:
msazhvi['Predictions'] = model.predict(msazhvi[['Education Score', 'Mean Income', 'Mean Property Tax', 'Mean Rent as a Percentage of Income']])
msazhvi['Difference'] = msazhvi['2018 ZHVI'] - msazhvi['Predictions']

In [49]:
print('R-Squared: ' + str(model.score(msazhvi[['Education Score', 'Mean Income', 'Mean Property Tax', 'Mean Rent as a Percentage of Income']], msazhvi['2018 ZHVI'])))

R-Squared: 0.676478348001411

In [50]:
edModel = LinearRegression()
edModel.fit(msazhvi[['Education Score']], msazhvi['2018 ZHVI'])
print('R-Squared: ' + str(edModel.score(msazhvi[['Education Score']], msazhvi['2018 ZHVI'])))

R-Squared: 0.2544382437983027

In [51]:
incModel = LinearRegression()
incModel.fit(msazhvi[['Mean Income']], msazhvi['2018 ZHVI'])
print('R-Squared: ' + str(incModel.score(msazhvi[['Mean Income']], msazhvi['2018 ZHVI'])))

R-Squared: 0.5701404271301895

In [52]:
taxModel = LinearRegression()
taxModel.fit(msazhvi[['Mean Property Tax']], msazhvi['2018 ZHVI'])
print('R-Squared: ' + str(taxModel.score(msazhvi[['Mean Property Tax']], msazhvi['2018 ZHVI'])))

R-Squared: 0.2519217030232943

In [53]:
rentModel = LinearRegression()
rentModel.fit(msazhvi[['Mean Rent as a Percentage of Income']], msazhvi['2018 ZHVI'])
print('R-Squared: ' + str(rentModel.score(msazhvi[['Mean Rent as a Percentage of Income']], msazhvi['2018 ZHVI'])))

R-Squared: 0.33959353209943466

In [62]:
%matplotlib notebook
from mpl_toolkits.mplot3d import Axes3D

twoDModel = LinearRegression()
twoDModel.fit(msazhvi[['Mean Income', 'Mean Rent as a Percentage of Income']], msazhvi['2018 ZHVI'])

inc_pred = np.linspace(60000, 140000, 200)
RPI_pred = np.linspace(9, 14, 200)

samples = pd.DataFrame({'Income':inc_pred, 'RPI':RPI_pred})

pred = twoDModel.predict([inc_pred, RPI_pred])

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(msazhvi['Mean Income'], msazhvi['Mean Rent as a Percentage of Income'], msazhvi['2018 ZHVI'], c='r')
ax.plot_surface(inc_pred, RPI_pred, pred)
ax.set_xlabel('Mean Income')
ax.set_ylabel('Mean Rent as a Percentage of Income')
ax.set_zlabel('2018 ZHVI')

plt.show()

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 200)

In [61]:
inc_pred

array([ 60000.        ,  60402.01005025,  60804.0201005 ,  61206.03015075,
        61608.04020101,  62010.05025126,  62412.06030151,  62814.07035176,
        63216.08040201,  63618.09045226,  64020.10050251,  64422.11055276,
        64824.12060302,  65226.13065327,  65628.14070352,  66030.15075377,
        66432.16080402,  66834.17085427,  67236.18090452,  67638.19095477,
        68040.20100503,  68442.21105528,  68844.22110553,  69246.23115578,
        69648.24120603,  70050.25125628,  70452.26130653,  70854.27135678,
        71256.28140704,  71658.29145729,  72060.30150754,  72462.31155779,
        72864.32160804,  73266.33165829,  73668.34170854,  74070.35175879,
        74472.36180905,  74874.3718593 ,  75276.38190955,  75678.3919598 ,
        76080.40201005,  76482.4120603 ,  76884.42211055,  77286.4321608 ,
        77688.44221106,  78090.45226131,  78492.46231156,  78894.47236181,
        79296.48241206,  79698.49246231,  80100.50251256,  80502.51256281,
        80904.52261307,  81306.53266332,  81708.54271357,  82110.55276382,
        82512.56281407,  82914.57286432,  83316.58291457,  83718.59296482,
        84120.60301508,  84522.61306533,  84924.62311558,  85326.63316583,
        85728.64321608,  86130.65326633,  86532.66331658,  86934.67336683,
        87336.68341709,  87738.69346734,  88140.70351759,  88542.71356784,
        88944.72361809,  89346.73366834,  89748.74371859,  90150.75376884,
        90552.7638191 ,  90954.77386935,  91356.7839196 ,  91758.79396985,
        92160.8040201 ,  92562.81407035,  92964.8241206 ,  93366.83417085,
        93768.84422111,  94170.85427136,  94572.86432161,  94974.87437186,
        95376.88442211,  95778.89447236,  96180.90452261,  96582.91457286,
        96984.92462312,  97386.93467337,  97788.94472362,  98190.95477387,
        98592.96482412,  98994.97487437,  99396.98492462,  99798.99497487,
       100201.00502513, 100603.01507538, 101005.02512563, 101407.03517588,
       101809.04522613, 102211.05527638, 102613.06532663, 103015.07537688,
       103417.08542714, 103819.09547739, 104221.10552764, 104623.11557789,
       105025.12562814, 105427.13567839, 105829.14572864, 106231.15577889,
       106633.16582915, 107035.1758794 , 107437.18592965, 107839.1959799 ,
       108241.20603015, 108643.2160804 , 109045.22613065, 109447.2361809 ,
       109849.24623116, 110251.25628141, 110653.26633166, 111055.27638191,
       111457.28643216, 111859.29648241, 112261.30653266, 112663.31658291,
       113065.32663317, 113467.33668342, 113869.34673367, 114271.35678392,
       114673.36683417, 115075.37688442, 115477.38693467, 115879.39698492,
       116281.40703518, 116683.41708543, 117085.42713568, 117487.43718593,
       117889.44723618, 118291.45728643, 118693.46733668, 119095.47738693,
       119497.48743719, 119899.49748744, 120301.50753769, 120703.51758794,
       121105.52763819, 121507.53768844, 121909.54773869, 122311.55778894,
       122713.5678392 , 123115.57788945, 123517.5879397 , 123919.59798995,
       124321.6080402 , 124723.61809045, 125125.6281407 , 125527.63819095,
       125929.64824121, 126331.65829146, 126733.66834171, 127135.67839196,
       127537.68844221, 127939.69849246, 128341.70854271, 128743.71859296,
       129145.72864322, 129547.73869347, 129949.74874372, 130351.75879397,
       130753.76884422, 131155.77889447, 131557.78894472, 131959.79899497,
       132361.80904523, 132763.81909548, 133165.82914573, 133567.83919598,
       133969.84924623, 134371.85929648, 134773.86934673, 135175.87939698,
       135577.88944724, 135979.89949749, 136381.90954774, 136783.91959799,
       137185.92964824, 137587.93969849, 137989.94974874, 138391.95979899,
       138793.96984925, 139195.9798995 , 139597.98994975, 140000.        ])